#!/usr/bin/env bash
#
#  author  : Jeong Han Lee
#  email   : jeonghan.lee@gmail.com
#  date    : Monday, June 29 01:35:40 PDT 2020
#  version : 0.0.2

declare -gr SC_SCRIPT="$(realpath "$0")"
declare -gr SC_SCRIPTNAME=${0##*/}
declare -gr SC_TOP="${SC_SCRIPT%/*}"
declare -gr LOGDATE="$(date +%y%m%d%H%M)"


function pushd { builtin pushd "$@" > /dev/null; }
function popd  { builtin popd  "$@" > /dev/null; }


CF_PORT="$1"

SRC_TOP=${SC_TOP}/../../

pushd ${SRC_TOP}

echo "docker build --network=host --file docker/Dockerfile -t ${LOGDATE} --build-arg CF_PORT_HTTP=${CF_PORT} ."

popd
